/**
 * Lifecycle email templates for the trial-lifecycle worker.
 *
 * Each function returns { subject, html } and embeds a one-click upgrade URL
 * generated by the caller. We don't generate the URL here so the worker can
 * cleanly sign + cache JWTs.
 *
 * Visual style follows the canonical AIWholesail email template established
 * in routes/auth.js (dark #0a0a0b card, #06b6d4 cyan accent bar + CTAs,
 * table-based layout for Outlook compatibility).
 */

const LOGO_URL = 'https://aiwholesail.com/logo-white.png';
const FOOTER_YEAR = new Date().getFullYear();

function shell({ headline, intro, body, cta, ctaUrl, footer }) {
  return `<!DOCTYPE html>
<html><body style="margin:0;padding:0;background:#000">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#000;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif">
  <tr><td align="center" style="padding:40px 20px">
    <table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#0a0a0b;border-radius:12px;overflow:hidden;border:1px solid #1a1a1a">
      <tr><td style="padding:28px 32px 20px;border-bottom:1px solid #1a1a1a">
        <img src="${LOGO_URL}" alt="AIWholesail" height="32" style="height:32px;width:auto;display:block" />
      </td></tr>
      <tr><td style="height:3px;background:linear-gradient(90deg,#06b6d4,#0891b2,#06b6d4);font-size:0;line-height:0">&nbsp;</td></tr>
      <tr><td style="padding:36px 32px 32px">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:28px">
          <tr><td style="color:#ffffff;font-size:26px;font-weight:700;letter-spacing:-0.5px;line-height:1.2;padding-bottom:12px">${headline}</td></tr>
          <tr><td style="color:#a3a3a3;font-size:16px;line-height:1.6">${intro}</td></tr>
        </table>
        ${body}
        <table cellpadding="0" cellspacing="0" border="0" style="margin:32px 0 8px">
          <tr><td style="background:#06b6d4;border-radius:8px">
            <a href="${ctaUrl}" style="display:inline-block;padding:14px 32px;color:#000;font-weight:700;font-size:15px;text-decoration:none;letter-spacing:-0.2px">${cta}</a>
          </td></tr>
        </table>
        <p style="color:#525252;font-size:12px;line-height:1.5;margin:20px 0 0">${footer || ''}</p>
      </td></tr>
      <tr><td style="padding:20px 32px 24px;border-top:1px solid #1a1a1a">
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr><td style="color:#404040;font-size:11px;line-height:1.5">
            &copy; ${FOOTER_YEAR} AIWholesail &middot; <a href="https://aiwholesail.com" style="color:#06b6d4;text-decoration:none">aiwholesail.com</a>
          </td></tr>
        </table>
      </td></tr>
    </table>
  </td></tr>
</table>
</body></html>`;
}

function statusBadge(color, text) {
  return `<table cellpadding="0" cellspacing="0" border="0" style="margin-bottom:20px"><tr>
    <td style="width:10px;height:10px;background:${color};border-radius:50%;font-size:0;line-height:0">&nbsp;</td>
    <td style="padding-left:10px;color:${color};font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.1em">${text}</td>
  </tr></table>`;
}

function detailsTable(rows) {
  const trs = rows.map(([label, value]) => `
    <tr><td style="padding:14px 0;border-bottom:1px solid #1a1a1a">
      <table width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td width="140" style="color:#525252;font-size:13px;font-weight:500">${label}</td>
          <td style="color:#e5e5e5;font-size:15px;font-weight:500">${value}</td>
        </tr>
      </table>
    </td></tr>`).join('');
  return `<table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 0">${trs}</table>`;
}

function nameOf(user) {
  return user.full_name?.split(' ')[0] || 'there';
}

function fmtDate(iso) {
  if (!iso) return '';
  return new Date(iso).toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
  });
}

// ───────────────── Day -1 (24h before trial expires) ─────────────────
function renderDayMinus1(user, upgradeUrl) {
  return {
    subject: `${nameOf(user)}, your AIWholesail trial ends tomorrow`,
    html: shell({
      headline: 'Your trial ends tomorrow',
      intro: `Hey ${nameOf(user)}, just a heads up — your 7-day Pro trial wraps up in ~24 hours. Upgrade now and you keep every alert, search, and saved deal you've set up. No price change, no recompute, no friction.`,
      body: `
        ${statusBadge('#06b6d4', 'Trial ending soon')}
        ${detailsTable([
          ['Plan', '<span style="color:#06b6d4">Pro</span> · $49/month'],
          ['Trial ends', fmtDate(user.trial_end)],
          ['What you keep', 'All alerts, AI deal scoring, saved properties, deal pipeline'],
        ])}
        <p style="color:#a3a3a3;font-size:14px;line-height:1.6;margin:24px 0 0">
          Upgrade with one click — we already know who you are. You'll be on Stripe checkout in 2 seconds.
        </p>
      `,
      cta: 'Lock in $49/mo →',
      ctaUrl: upgradeUrl,
      footer: `If the button doesn't work, copy this URL into your browser: ${upgradeUrl}`,
    }),
  };
}

// ───────────────── Day 0 (just expired) ─────────────────
function renderDayZero(user, upgradeUrl) {
  return {
    subject: 'Your AIWholesail trial just ended — restore in one click',
    html: shell({
      headline: 'Your trial just ended',
      intro: `${nameOf(user)}, your 7-day Pro trial wrapped up. Your account stays — alerts, saved deals, search history, all of it — but premium features are paused until you upgrade. One click and you're back.`,
      body: `
        ${statusBadge('#a3a3a3', 'Trial ended')}
        ${detailsTable([
          ['Plan to restore', '<span style="color:#06b6d4">Pro</span> · $49/month'],
          ['What stays', 'Alerts, saved deals, search history, AI scores'],
          ['What pauses', 'New searches, fresh AI rankings, deal alerts'],
        ])}
        <p style="color:#a3a3a3;font-size:14px;line-height:1.6;margin:24px 0 0">
          Most members close their first wholesale deal in week 1-2 of paid. Don't let momentum stall.
        </p>
      `,
      cta: 'Restore access · $49/mo →',
      ctaUrl: upgradeUrl,
      footer: `Direct link: ${upgradeUrl}`,
    }),
  };
}

// ───────────────── Day +1 (1 day after trial ended) ─────────────────
function renderDayPlus1(user, upgradeUrl) {
  return {
    subject: `${nameOf(user)}, you're 24 hours past your trial`,
    html: shell({
      headline: 'Yesterday your trial ended',
      intro: `Most users who restore do it in the first 24-48 hours, while everything they've set up is still fresh. ${nameOf(user)}, this is that window for you.`,
      body: `
        ${statusBadge('#f59e0b', 'Reminder')}
        <p style="color:#a3a3a3;font-size:14px;line-height:1.6;margin:0 0 16px">
          During your trial you got access to AI deal scoring, real-time spread alerts, and the deal pipeline.
          Everything you set up is preserved on your account — your alerts, saved searches, and pipeline status
          all snap back the moment you upgrade.
        </p>
        ${detailsTable([
          ['Restore plan', '<span style="color:#06b6d4">Pro</span> · $49/month'],
          ['Setup time', '~30 seconds'],
        ])}
      `,
      cta: 'Restore for $49/mo →',
      ctaUrl: upgradeUrl,
      footer: `Not what you were expecting? Reply to this email — we read every one.`,
    }),
  };
}

// ───────────────── Day +7 (1 week after trial ended) ─────────────────
function renderDayPlus7(user, upgradeUrl) {
  return {
    subject: 'Last call: your AIWholesail account stays warm for now',
    html: shell({
      headline: 'Last call before we cool your account',
      intro: `Hey ${nameOf(user)} — it's been a week since your AIWholesail trial wrapped. Your account, alerts, and saved deals are still warm. If you want to come back, this is the easiest moment.`,
      body: `
        ${statusBadge('#dc2626', 'Final reminder')}
        <p style="color:#a3a3a3;font-size:14px;line-height:1.6;margin:0 0 16px">
          We're not going anywhere — but every day that passes, the deals you'd be alerted to are getting picked
          off by other investors. The wholesalers winning right now are the ones with always-on alerts in the
          markets they care about.
        </p>
        ${detailsTable([
          ['Restore plan', '<span style="color:#06b6d4">Pro</span> · $49/month'],
          ['Cancel anytime', 'No commitment, no contract'],
          ['Account state', 'Still preserved — your alerts and saved deals snap back'],
        ])}
      `,
      cta: 'Bring my account back →',
      ctaUrl: upgradeUrl,
      footer: `Or reply to this email and tell us what'd make AIWholesail a better fit.`,
    }),
  };
}

module.exports = {
  renderDayMinus1,
  renderDayZero,
  renderDayPlus1,
  renderDayPlus7,
};
