/**
 * Lifecycle email templates for the trial-lifecycle worker.
 *
 * Each function returns { subject, html } and embeds a one-click upgrade URL
 * generated by the caller. We don't generate the URL here so the worker can
 * cleanly sign + cache JWTs.
 *
 * Visual style follows the canonical AIWholesail email template established
 * in routes/auth.js (dark #0a0a0b card, #06b6d4 cyan accent bar + CTAs,
 * table-based layout for Outlook compatibility).
 */

const LOGO_URL = 'https://aiwholesail.com/logo-aiw-email.png';
const FOOTER_YEAR = new Date().getFullYear();
const FOUNDER_EMAIL = 'connor@aiwholesail.com';
const FOUNDER_PHONE = '248-881-4147';

/**
 * Branded signature block — appended to founder-personal emails.
 * Logo + name + role + website + reply-to email + phone.
 */
function founderSignature() {
  return `
<table cellpadding="0" cellspacing="0" border="0" style="margin:32px 0 0;border-top:1px solid #1a1a1a;padding-top:20px;width:100%">
  <tr>
    <td style="padding-right:14px;vertical-align:top;width:48px">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr><td style="background:#0a0a0b;border:1px solid #1a1a1a;border-radius:10px;padding:8px;width:48px;height:48px;text-align:center">
          <img src="${LOGO_URL}" alt="AIWholesail" height="32" style="display:block;height:32px;width:auto;margin:0 auto" />
        </td></tr>
      </table>
    </td>
    <td style="vertical-align:top;border-left:2px solid #06b6d4;padding-left:14px">
      <p style="margin:0;color:#ffffff;font-size:15px;font-weight:600;letter-spacing:-0.2px;line-height:1.2">Connor O'Dea</p>
      <p style="margin:2px 0 0;color:#06b6d4;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.12em;line-height:1.3">Founder &amp; CEO</p>
      <p style="margin:8px 0 0;color:#737373;font-size:12px;line-height:1.6">
        <a href="https://aiwholesail.com" style="color:#06b6d4;text-decoration:none">aiwholesail.com</a>
        &nbsp;·&nbsp;
        <a href="mailto:${FOUNDER_EMAIL}" style="color:#a3a3a3;text-decoration:none">${FOUNDER_EMAIL}</a>
        &nbsp;·&nbsp;
        <a href="tel:+1${FOUNDER_PHONE.replace(/-/g,'')}" style="color:#a3a3a3;text-decoration:none">${FOUNDER_PHONE}</a>
      </p>
    </td>
  </tr>
</table>`;
}

function shell({ headline, intro, body, cta, ctaUrl, footer }) {
  return `<!DOCTYPE html>
<html><head><style>@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap');</style></head><body style="margin:0;padding:0;background:#000">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#000;font-family:'Montserrat',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif">
  <tr><td align="center" style="padding:40px 20px">
    <table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#0a0a0b;border-radius:12px;overflow:hidden;border:1px solid #1a1a1a">
      <tr><td style="padding:28px 32px 20px;border-bottom:1px solid #1a1a1a">
        <img src="${LOGO_URL}" alt="AIWholesail" height="32" style="height:32px;width:auto;display:block" />
      </td></tr>
      <tr><td style="height:3px;background:linear-gradient(90deg,#06b6d4,#0891b2,#06b6d4);font-size:0;line-height:0">&nbsp;</td></tr>
      <tr><td style="padding:36px 32px 32px">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:28px">
          <tr><td style="color:#ffffff;font-size:26px;font-weight:700;letter-spacing:-0.5px;line-height:1.2;padding-bottom:12px">${headline}</td></tr>
          <tr><td style="color:#a3a3a3;font-size:16px;line-height:1.6">${intro}</td></tr>
        </table>
        ${body}
        <table cellpadding="0" cellspacing="0" border="0" style="margin:32px 0 8px">
          <tr><td style="background:#06b6d4;border-radius:8px">
            <a href="${ctaUrl}" style="display:inline-block;padding:14px 32px;color:#000;font-weight:700;font-size:15px;text-decoration:none;letter-spacing:-0.2px">${cta}</a>
          </td></tr>
        </table>
        <p style="color:#525252;font-size:12px;line-height:1.5;margin:20px 0 0">${footer || ''}</p>
      </td></tr>
      <tr><td style="padding:20px 32px 24px;border-top:1px solid #1a1a1a">
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr><td style="color:#404040;font-size:11px;line-height:1.5">
            &copy; ${FOOTER_YEAR} AIWholesail &middot; <a href="https://aiwholesail.com" style="color:#06b6d4;text-decoration:none">aiwholesail.com</a>
          </td></tr>
        </table>
      </td></tr>
    </table>
  </td></tr>
</table>
</body></html>`;
}

function statusBadge(color, text) {
  return `<table cellpadding="0" cellspacing="0" border="0" style="margin-bottom:20px"><tr>
    <td style="width:10px;height:10px;background:${color};border-radius:50%;font-size:0;line-height:0">&nbsp;</td>
    <td style="padding-left:10px;color:${color};font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.1em">${text}</td>
  </tr></table>`;
}

function detailsTable(rows) {
  const trs = rows.map(([label, value]) => `
    <tr><td style="padding:14px 0;border-bottom:1px solid #1a1a1a">
      <table width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td width="140" style="color:#525252;font-size:13px;font-weight:500">${label}</td>
          <td style="color:#e5e5e5;font-size:15px;font-weight:500">${value}</td>
        </tr>
      </table>
    </td></tr>`).join('');
  return `<table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 0">${trs}</table>`;
}

function nameOf(user) {
  return user.full_name?.split(' ')[0] || 'there';
}

function fmtDate(iso) {
  if (!iso) return '';
  return new Date(iso).toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
  });
}

// ───────────────── Founder welcome (~24-48h after signup) ─────────────────
// Personal note from Connor. No upgrade CTA — this is purely about
// relationship-building and feedback collection. Replies route back to
// connor@aiwholesail.com via Reply-To (forwarded by ImprovMX to Connor's
// Gmail) so the user can text/email/call him directly.
function renderFounderWelcome(user) {
  const first = nameOf(user);

  return {
    subject: `${first}, a quick note from Connor (founder of AIWholesail)`,
    html: `<!DOCTYPE html>
<html><head><style>@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap');</style></head><body style="margin:0;padding:0;background:#000">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#000;font-family:'Montserrat',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif">
  <tr><td align="center" style="padding:40px 20px">
    <table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#0a0a0b;border-radius:12px;overflow:hidden;border:1px solid #1a1a1a">
      <tr><td style="padding:28px 32px 20px;border-bottom:1px solid #1a1a1a">
        <img src="${LOGO_URL}" alt="AIWholesail" height="32" style="height:32px;width:auto;display:block" />
      </td></tr>
      <tr><td style="height:3px;background:linear-gradient(90deg,#06b6d4,#0891b2,#06b6d4);font-size:0;line-height:0">&nbsp;</td></tr>
      <tr><td style="padding:36px 32px 32px">
        ${statusBadge('#06b6d4', 'A note from the founder')}
        <h1 style="color:#ffffff;font-size:24px;font-weight:700;letter-spacing:-0.5px;line-height:1.25;margin:0 0 22px">
          Hey ${first} — thanks for signing up.
        </h1>
        <p style="color:#d4d4d4;font-size:15px;line-height:1.7;margin:0 0 18px">
          I'm Connor, the founder of AIWholesail. I wanted to reach out personally and say thanks for trying us out.
        </p>
        <p style="color:#d4d4d4;font-size:15px;line-height:1.7;margin:0 0 18px">
          I'll be straight with you: <strong style="color:#ffffff">we're new software.</strong> A lot of what we've built is working, some of it is rough, and some of the most important features are still being shaped. The investors who give us feedback in this window have an outsized influence on where the product goes next.
        </p>
        <p style="color:#d4d4d4;font-size:15px;line-height:1.7;margin:0 0 22px">
          So I'd genuinely appreciate three things:
        </p>
        <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 26px">
          <tr><td style="padding:0 0 12px">
            <table cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td valign="top" style="color:#06b6d4;font-size:15px;padding-right:10px;padding-top:1px">&#9679;</td>
                <td style="color:#e5e5e5;font-size:14px;line-height:1.55"><strong style="color:#ffffff">What's working</strong> — what part of AIWholesail is genuinely useful for your deal flow?</td>
              </tr>
            </table>
          </td></tr>
          <tr><td style="padding:0 0 12px">
            <table cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td valign="top" style="color:#06b6d4;font-size:15px;padding-right:10px;padding-top:1px">&#9679;</td>
                <td style="color:#e5e5e5;font-size:14px;line-height:1.55"><strong style="color:#ffffff">What's missing</strong> — what would make this a no-brainer to pay for?</td>
              </tr>
            </table>
          </td></tr>
          <tr><td>
            <table cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td valign="top" style="color:#06b6d4;font-size:15px;padding-right:10px;padding-top:1px">&#9679;</td>
                <td style="color:#e5e5e5;font-size:14px;line-height:1.55"><strong style="color:#ffffff">What's broken</strong> — anything weird, slow, confusing, or just plain wrong?</td>
              </tr>
            </table>
          </td></tr>
        </table>

        <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 22px;background:rgba(6,182,212,0.06);border:1px solid rgba(6,182,212,0.20);border-radius:10px">
          <tr><td style="padding:18px 20px">
            <p style="color:#06b6d4;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.1em;margin:0 0 4px">Reach me directly</p>
            <p style="color:#ffffff;font-size:18px;font-weight:600;letter-spacing:-0.2px;margin:0 0 8px">
              <a href="tel:+12488814147" style="color:#ffffff;text-decoration:none">${FOUNDER_PHONE}</a>
            </p>
            <p style="color:#a3a3a3;font-size:13px;line-height:1.5;margin:0">
              Text or call. Seriously — I pick up. Or just reply to this email; it goes to my inbox.
            </p>
          </td></tr>
        </table>

        <p style="color:#a3a3a3;font-size:14px;line-height:1.65;margin:0 0 6px">
          Even one sentence helps. The product gets sharper every time someone tells me what's wrong with it.
        </p>
        ${founderSignature()}
      </td></tr>
      <tr><td style="padding:20px 32px 24px;border-top:1px solid #1a1a1a">
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td style="color:#404040;font-size:11px;line-height:1.5">
              &copy; ${FOOTER_YEAR} AIWholesail &middot; <a href="https://aiwholesail.com" style="color:#06b6d4;text-decoration:none">aiwholesail.com</a>
            </td>
            <td align="right" style="color:#404040;font-size:11px">
              <a href="mailto:${FOUNDER_EMAIL}" style="color:#404040;text-decoration:none">${FOUNDER_EMAIL}</a>
            </td>
          </tr>
        </table>
      </td></tr>
    </table>
  </td></tr>
</table>
</body></html>`,
  };
}

// ───────────────── Day -1 (24h before trial expires) ─────────────────
function renderDayMinus1(user, upgradeUrl) {
  return {
    subject: `${nameOf(user)}, your AIWholesail trial ends tomorrow`,
    html: shell({
      headline: 'Your trial ends tomorrow',
      intro: `Hey ${nameOf(user)}, just a heads up — your 7-day Pro trial wraps up in ~24 hours. Upgrade now and you keep every alert, search, and saved deal you've set up. No price change, no recompute, no friction.`,
      body: `
        ${statusBadge('#06b6d4', 'Trial ending soon')}
        ${detailsTable([
          ['Plan', '<span style="color:#06b6d4">Pro</span> · $49/month'],
          ['Trial ends', fmtDate(user.trial_end)],
          ['What you keep', 'All alerts, AI deal scoring, saved properties, deal pipeline'],
        ])}
        <p style="color:#a3a3a3;font-size:14px;line-height:1.6;margin:24px 0 0">
          Upgrade with one click — we already know who you are. You'll be on Stripe checkout in 2 seconds.
        </p>
      `,
      cta: 'Lock in $49/mo →',
      ctaUrl: upgradeUrl,
      footer: `If the button doesn't work, copy this URL into your browser: ${upgradeUrl}`,
    }),
  };
}

// ───────────────── Day 0 (just expired) ─────────────────
function renderDayZero(user, upgradeUrl) {
  return {
    subject: 'Your AIWholesail trial just ended — restore in one click',
    html: shell({
      headline: 'Your trial just ended',
      intro: `${nameOf(user)}, your 7-day Pro trial wrapped up. Your account stays — alerts, saved deals, search history, all of it — but premium features are paused until you upgrade. One click and you're back.`,
      body: `
        ${statusBadge('#a3a3a3', 'Trial ended')}
        ${detailsTable([
          ['Plan to restore', '<span style="color:#06b6d4">Pro</span> · $49/month'],
          ['What stays', 'Alerts, saved deals, search history, AI scores'],
          ['What pauses', 'New searches, fresh AI rankings, deal alerts'],
        ])}
        <p style="color:#a3a3a3;font-size:14px;line-height:1.6;margin:24px 0 0">
          Most members close their first wholesale deal in week 1-2 of paid. Don't let momentum stall.
        </p>
      `,
      cta: 'Restore access · $49/mo →',
      ctaUrl: upgradeUrl,
      footer: `Direct link: ${upgradeUrl}`,
    }),
  };
}

// ───────────────── Day +1 (1 day after trial ended) ─────────────────
function renderDayPlus1(user, upgradeUrl) {
  return {
    subject: `${nameOf(user)}, you're 24 hours past your trial`,
    html: shell({
      headline: 'Yesterday your trial ended',
      intro: `Most users who restore do it in the first 24-48 hours, while everything they've set up is still fresh. ${nameOf(user)}, this is that window for you.`,
      body: `
        ${statusBadge('#f59e0b', 'Reminder')}
        <p style="color:#a3a3a3;font-size:14px;line-height:1.6;margin:0 0 16px">
          During your trial you got access to AI deal scoring, real-time spread alerts, and the deal pipeline.
          Everything you set up is preserved on your account — your alerts, saved searches, and pipeline status
          all snap back the moment you upgrade.
        </p>
        ${detailsTable([
          ['Restore plan', '<span style="color:#06b6d4">Pro</span> · $49/month'],
          ['Setup time', '~30 seconds'],
        ])}
      `,
      cta: 'Restore for $49/mo →',
      ctaUrl: upgradeUrl,
      footer: `Not what you were expecting? Reply to this email — we read every one.`,
    }),
  };
}

// ───────────────── Day +7 (1 week after trial ended) ─────────────────
function renderDayPlus7(user, upgradeUrl) {
  return {
    subject: 'Last call: your AIWholesail account stays warm for now',
    html: shell({
      headline: 'Last call before we cool your account',
      intro: `Hey ${nameOf(user)} — it's been a week since your AIWholesail trial wrapped. Your account, alerts, and saved deals are still warm. If you want to come back, this is the easiest moment.`,
      body: `
        ${statusBadge('#dc2626', 'Final reminder')}
        <p style="color:#a3a3a3;font-size:14px;line-height:1.6;margin:0 0 16px">
          We're not going anywhere — but every day that passes, the deals you'd be alerted to are getting picked
          off by other investors. The wholesalers winning right now are the ones with always-on alerts in the
          markets they care about.
        </p>
        ${detailsTable([
          ['Restore plan', '<span style="color:#06b6d4">Pro</span> · $49/month'],
          ['Cancel anytime', 'No commitment, no contract'],
          ['Account state', 'Still preserved — your alerts and saved deals snap back'],
        ])}
      `,
      cta: 'Bring my account back →',
      ctaUrl: upgradeUrl,
      footer: `Or reply to this email and tell us what'd make AIWholesail a better fit.`,
    }),
  };
}

module.exports = {
  renderFounderWelcome,
  renderDayMinus1,
  renderDayZero,
  renderDayPlus1,
  renderDayPlus7,
};
